global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: 'dispositivos_iot_resources'
    static_configs:
      - targets: ['10.10.10.3:9100', '10.10.10.4:9100', '10.10.10.5:9100']

  
  - job_name: 'blackbox_iot_devices'
    metrics_path: /probe
    params:
      module: [icmp_probe]
    static_configs:
      - targets:
        - '10.10.10.3'  
        - '10.10.10.4'  
        - '10.10.10.5'  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.10.20.5:9115 

  
  - job_name: 'blackbox_network_infra'
    metrics_path: /probe
    params:
      module: [icmp_probe]
    static_configs:
      - targets:
        - '10.10.10.1'  # Gateway/Roteador (Lado IoT)
        - '10.10.20.1'  # Gateway/Roteador (Lado Serviços)
        - '10.10.20.2'  # Broker MQTT (Serviço Crítico)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.10.20.5:9115 # Endereço do blackbox-exporter
