{
 "title": "SmartCity IoT Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Qualidade da Rede (Latência, Jitter e Perda)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latência (Dispositivos IoT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_iot_devices\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jitter (Dispositivos IoT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "stddev_over_time(probe_duration_seconds{job=\"blackbox_iot_devices\"}[1m]) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Perda de Pacotes (Dispositivos IoT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg_over_time(probe_success{job=\"blackbox_iot_devices\"}[5m]) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Recursos por Dispositivo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uso de CPU por Dispositivo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (rate(node_cpu_seconds_total{job=\"dispositivos_iot_resources\", mode=\"idle\"}[2m]))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uso de Memória por Dispositivo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"dispositivos_iot_resources\"} / node_memory_MemTotal_bytes{job=\"dispositivos_iot_resources\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uso de Disco por Dispositivo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{job=\"dispositivos_iot_resources\",mountpoint=\"/\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{job=\"dispositivos_iot_resources\",mountpoint=\"/\",fstype!=\"rootfs\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}